version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=DjangoProject.settings
      - SECRET_KEY=admin
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 DjangoProject.asgi:application"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

volumes:
  postgres_data: