# Generated by Django 5.2.1 on 2025-05-23 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='receiver',
            field=models.ForeignKey(blank=True, help_text='Указывает реального пользователя (если чат не с GPT).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
