# Generated by Django 5.2.1 on 2025-05-14 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('play_music', models.BooleanField(default=True)),
                ('notify_contact', models.BooleanField(default=True)),
                ('notify_therapist', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='event.alarmscenario')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('music_played', models.BooleanField(default=False)),
                ('message_sent_to_contacts', models.BooleanField(default=False)),
                ('voice_message_played', models.BooleanField(default=False)),
                ('therapist_notified', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('alarm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='event.alarm')),
            ],
        ),
    ]
