# Generated by Django 5.2.1 on 2025-05-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ptsd_level',
            field=models.IntegerField(blank=True),
        ),
    ]
