# Generated by Django 5.2.1 on 2025-05-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userinfo_ptsd_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ptsd_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
